AppHttpClient/Controllers/CustomerMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net;
using System.Threading.Tasks;
namespace AppHttpClient.Controllers
{ 

    [Route("CustomerMaster/")]
    public class CustomerMasterController : Controller
    {
        // GET: CustomerMaster
        [HttpGet]
        [Route("GetAllCustomer")]
        public async Task<ActionResult> GetAllCustomer()
        {
            using(var client=new HttpClient())
             {
            client.BaseAddress = new Uri("http://localhost:62937/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            //Get Method
            HttpResponseMessage response =await client.GetAsync("GetAllCustomer");
            if(response.IsSuccessStatusCode)
            {
                var cust=await response.Content.ReadAsAsync<CustomerMaster[]>();

                return View(cust);
            }
                else
                {
                    return Content("No Data" );
                }
           
            }
        
        }

        [HttpGet]
        [Route("GetCustomerById/{id}")]
        public async Task<ActionResult> GetCustomerById(int id)
        {

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:62937/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                //Get Method
                HttpResponseMessage response = await client.GetAsync($"GetCustomerById/{id}");
                if (response.IsSuccessStatusCode)
                {
                    var cust = await response.Content.ReadAsAsync<CustomerMaster>();

                    return View(cust);
                }
                else
                {
                    ViewBag.Error();
                    return Content("No Data");
                }

            }
        }

        [HttpGet]
        [Route("SaveCustomer")]
        public async Task<ActionResult> SaveCustomer()
        {
            return View();
        }

        [HttpPost]
        [Route("SaveCust")]
        public async Task<ActionResult> SaveCustomer(CustomerMaster customer)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:62937/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                //Get Method
                HttpResponseMessage response = await client.PostAsJsonAsync("SaveCust", customer);
                if (response.IsSuccessStatusCode)
                {

                    return RedirectToAction("GetAllCustomer");
                }
                else
                {
                    return View("SaveCustomer");
                }

            }
        }

        [HttpPost]
        [Route("DeleteCustomer/{id}")]
        public async Task<ActionResult> DeleteCustomer(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:62937/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                //Get Method
                HttpResponseMessage response = await client.DeleteAsync($"DeleteCustomer/{id}");
                if (response.IsSuccessStatusCode)
                {

                    return RedirectToAction("GetAllCustomer");
                }
                else
                {
                    return View("DeleteCustomer");
                }

            }
 
        }
        [HttpPost]
        [Route("UpdateCustomer")]
        public async Task<ActionResult> UpdateCustomer(CustomerMaster customer)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:62937/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                //Get Method
                HttpResponseMessage response = await client.PutAsJsonAsync($"UpdateCustomer",customer);
                if (response.IsSuccessStatusCode)
                {

                    return RedirectToAction("GetAllCustomer");
                }
                else
                {
                    return View("UpdateCustomer");
                }

            }
        }
    }
}

AppHttpClient/Views/CustomerMaster/DeleteCustomer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeleteCustomer</title>
</head>
<body>
    <div> 
        <h1>DataDeleted Successfully</h1>
    </div>
</body>
</html>

AppHttpClient/Views/CustomerMaster/GetAllCustomer.cshtml
@model IEnumerable<DataAccessLayer.CustomerMaster>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetAllCustomer</title>
</head>
<body>
    <h3>List Of Customer</h3>
    <div>
    <table>
        @foreach(var cust in Model)
            {
        <tr>
            <td>@cust.CustId</td>
            <td>@cust.FirstName</td>
            <td>@cust.LastName</td>
            <td>@cust.City</td>
            <td>@cust.States</td>
            <td>@cust.ContactNo</td>
            <td>@cust.Country</td>
            <td>@cust.Email</td>
        </tr>
            }
    </table>
    </div>
</body>
</html>

AppHttpClient/Views/CustomerMaster/GetCustomerById.cshtml
@model DataAccessLayer.CustomerMaster
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetCustomerById</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h2>Customer Id Info</h2>
        <div>
            <table class="table table-hover">
                <tr class="table-primary">
                    <th>CustId</th>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>Email/th>
                    <th>City</th>
                    <th>States</th>
                    <th>ContactNo</th>
                </tr>
                <tr>
                    <td>@Model.CustId</td>
                    <td>@Model.FirstName</td>
                    <td>@Model.LastName</td>
                    <td>@Model.Email/td>
                    <td>@Model.City</td>
                    <td>@Model.States</td>
                    <td>@Model.ContactNo</td>
                </tr>

            </table>
        </div>
    </div>
</body>
</html>

AppHttpClient/Views/CustomerMaster/SaveCustomer.cshtml
@model DataAccessLayer.CustomerMaster
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SaveCustomer</title>
</head>
<body>
    <h3>Details</h3>
    <div>
        @using (Html.BeginForm("SaveCust", "CustomerMaster", FormMethod.Post))
        {
            <div>
                @Html.Label("CustomerId: ")
                @Html.TextBoxFor(x => x.CustId)
            </div>

            <div>
                @Html.Label("FirstName ")
                @Html.TextBoxFor(x => x.FirstName)
            </div>
            <div>
                @Html.Label("LastName ")
                @Html.TextBoxFor(x => x.LastName)
            </div>
            <div>
                @Html.Label("Email ")
                @Html.TextBoxFor(x => x.Email)
            </div>
            <div>
                @Html.Label("ContactNo ")
                @Html.TextBoxFor(x => x.ContactNo)
            </div>
            <div>
                @Html.Label("Country ")
                @Html.TextBoxFor(x => x.Country)
            </div>
            <div>
                @Html.Label("State ")
                @Html.TextBoxFor(x => x.States)
            </div>
            <div>
                @Html.Label("City ")
                @Html.TextBoxFor(x => x.City)
            </div>
            <input type="submit" value="send" />
        }


    </div>
</body>
</html>